## QQ邮箱配置
spring:
  mail:
    #发送邮件服务器
    host: smtp.qq.com
    #发送邮件的邮箱地址
    username: 1352425876@qq.com
    #客户端授权码，不是邮箱密码，在qq邮箱设置里面自动生成
    password: uicwmsfqetytfifb
    # 发送邮件的地址，和上面username一致
    from: 1352425876@qq.com
    protocol: smtp
    default-encoding: UTF-8
    #以下可以配置或者不配置
    properties:
      mail:
        smtp:
          #端口号465或587
          port: 587
          auth: true
        starttls:
          enable: true
          required: true