#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/haodebar?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    # redis服务器的登录密码 没有可以不配置
#    password:
#    lettuce:
#      max-active: 8
#      max-idle: 8
#      max-wait: -1
#      min-idle: 0
#    timeout: 100
#  kafka:
#    binder:
#      #zk服务地址，集群部署的时候需要配置多个，
#      zk-nodes: localhost:2181,localhost:2182,localhost:2183
#    #kafka服务地址，集群部署的时候需要配置多个，
#    bootstrap-servers: localhost:9092
#    producer:
#      acks: -1
#      retries: 1
#      batch-size: 16384
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#    consumer:
#      enable-auto-commit: true
#      auto-commit-interval: 1000
#  elasticsearch:
#    host: 127.0.0.1
#    port: 9200
#    rest:
#      uris: 127.0.0.1:9200
#
#  cloud:
#    stream:
#      bindings:
#        #配置自己定义的通道与哪个中间件交互
#        steam-input: #MessageChannel里Input和Output的值
#          destination: xzc #目标主题 相当于kafka的topic
#          binder: kafka
#        steam-output:
#          destination: xzc #本例子创建了另外一个topic （test1）用于区分不同的功能区分。
#          binder: kafka
#      default-binder: kafka #默认的binder是kafka
#
#
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#      table-prefix: t_
#      table-underline: true
#      logic-delete-field: enable
#      logic-delete-value: 0
#      logic-not-delete-value: 1

#spring:
#  main:
#    lazy-initialization: true

#management:
#  endpoint:
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  metrics:
#    export:
#      prometheus:
#        enabled: true